apiVersion: apps/v1
kind: Deployment
metadata:
  name: inlogikapp-deployment
  labels:
    app: aspnetapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: mcr.microsoft.com/dotnet/samples:aspnetapp  # ASP.NET Core sample image
        ports:
        - containerPort: 8080
