apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetcore-sample
  template:
    metadata:
      labels:
        app: aspnetcore-sample
    spec:
      containers:
      - name: aspnetcore-sample
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        ports:
        - containerPort: 8080
